[package]
name = "lame"
version = "0.7.0"
authors = ["treetertot <europajuice@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "*"
parking_lot = "*"
lazy_static = "1.4"
num_cpus = "*"
